<h2>Quiz Time!</h2>
<p>::questionArea::</p>
<div id="questionContainer">
  <div
    class="questionBox"
    onclick="answerQuiz(this)"
    data-truthCheck="::truthCheck1::"
  >
    <p>::answer_1::</p>
  </div>
  <div
    class="questionBox"
    onclick="answerQuiz(this)"
    data-truthCheck="::truthCheck2::"
  >
    <p>::answer_2::</p>
  </div>
  <div
    class="questionBox"
    onclick="answerQuiz(this)"
    data-truthCheck="::truthCheck3::"
  >
    <p>::answer_3::</p>
  </div>
  <div
    class="questionBox"
    onclick="answerQuiz(this)"
    data-truthCheck="::truthCheck4::"
  >
    <p>::answer_4::</p>
  </div>
</div>
<?php
include_once("../components/navigation.html");
?>